### ISSUE TITLE
Nested Triggers

### ISSUE THREAD

**Issue by lperezdude** [reachtokish/rctx-contextmenu#23] opened 2021-07-07 13:59 UTC
- `rctx-contextmenu` version: 1.3.4
- `node` version: 16.3.0
- `npm` (or `yarn`) version: npm: 7.15.1

**Relevant code or config**
```JSX
<>
<ContextMenuTrigger id={menuOne}>
       ....
              <ContextMenuTrigger id={menuTwo}>
              .....
              </ContextMenuTrigger>
          ...
</ContextMenuTrigger>
      <ContextMenu id={menuOne}>
        ... menu 1
      </ContextMenu>
      <ContextMenu id={menuTwo}>
        .... menu 2
      </ContextMenu>
</>
```

**What you did:**
I'm trying to have a trigger inside another trigger, i figured the nested item would get the click event first. 
**What happened:**
When tried to right click the trigger 2  menu 1 comes up
**Problem description:**
When tried to right click the trigger 2  menu 1 comes up. 
**Suggested solution:**
Have nested triggers work properly inside other triggers.

**Comment by lperezdude** [comment] 2021-07-07 14:06
Sorry the code was deleted by the mark down
```JSX
<ContextMenuTrigger id={menuOne}>
   <ContextMenuTrigger id={menuTwo}>
  </ContextMenuTrigger>
</ContextMenuTrigger>
<ContextMenu id={menuOne}>
        ... Menu One
</ContextMenu>
<ContextMenu id={menuTwo}>
          ... Menu Two
</ContextMenu>
```

**Comment by reachtokish** [comment] 2021-07-11 08:31
Hi @lperezdude, thanks for reporting the issue. Let me check the issue and resolve it.

**Comment by reachtokish** [comment] 2021-07-11 13:55
Hey @lperezdude, the issue is resolved in the current version of the library which is [1.3.5](https://www.npmjs.com/package/rctx-contextmenu/v/1.3.5). Kindly update the version of the library inside your app. I've added an example as well.

Closing the issue. Kindly reopen it if you get the issue again.

**Closed** 2021-07-11 13:56 UTC
